[project]
name = "langgraph-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langgraph>=1.0.9",
    "notebook>=7.5.4",
    "python-dotenv>=1.2.1",
]
